MODEL:
  BERT_CKPT: "hfl/chinese-macbert-base"
  DEVICE: "cuda:1"
  NAME: "macbert4csc"
  # [loss_coefficient]
  HYPER_PARAMS: [ 1.0 ]
  GPU_IDS: [1]
  WEIGHTS: "epoch=6-val_loss=0.07.ckpt"

DATASETS:
  TRAIN: "datasets/csc/train.json"
  VALID: "datasets/csc/dev.json"
  TEST: "datasets/csc/test.json"

SOLVER:
  BASE_LR: 0.00001
  WEIGHT_DECAY: 0.00001
  BATCH_SIZE: 8
  WARMUP_EPOCHS: 8
  MAX_EPOCHS: 20
  ACCUMULATE_GRAD_BATCHES: 16


TEST:
  BATCH_SIZE: 8

TASK:
  NAME: "csc"

OUTPUT_DIR: "checkpoints/macbert4csc"
MODE: ["test" ]
